module.exports =  {
    FORM_ANUNCIO : 'FORM_ANUNCIO',
    PROPRIETARIO_VEI : 'PROPRIETARIO_VEI',
    VEICULO_VEI : 'VEICULO_VEI',
    INFORMCOES_VEI : 'INFORMCOES_VEI',
    IMAGEM_VEI : 'IMAGEM_VEI'
}
 